// Exercise names sourced from a weightlifting workout log dataset.
// Used to power the searchable exercise picker instead of free-text entry.

export const EXERCISE_LIST: string[] = [
    "Bench Press (Barbell)",
    "Bent Over Row (Dumbbell)",
    "Bicep Curl (Barbell)",
    "Bicep Curl (Dumbbell)",
    "Cable Fly",
    "Chin Up",
    "Curl Dumbbell",
    "Cycling",
    "Deadlift",
    "Deadlift (Barbell)",
    "Deadlift - Trap Bar",
    "Face pull",
    "Front Raise (Dumbbell)",
    "Front Squat (Barbell)",
    "Glute extension",
    "Good Morning",
    "Good Morning (Barbell)",
    "Hack Squat",
    "Hammer Curl",
    "Hammer Curl (Dumbbell)",
    "Hammer Decline Chest Press",
    "Hammer High Row - 1 Arm",
    "Hammer Row - Wide Grip",
    "Hammer Row Stand 1armed",
    "Hammer back row wide 45 angle",
    "Hammer lat pulldown",
    "Hammer seated row",
    "Hammer seated row (CLOSE GRIP)",
    "Hammer shoulder press",
    "Incline Bench Press",
    "Incline Bench Press (Barbell)",
    "Incline Press (Dumbbell)",
    "Landmine Press",
    "Lat Pulldown",
    "Lat Pulldown (Cable)",
    "Lat Pulldown Closegrip",
    "Lateral Raise",
    "Lateral Raise (Dumbbell)",
    "Lateral Raise (Dumbbells)",
    "Leg Extension (Machine)",
    "Leg curl",
    "Leg outward fly",
    "Leg press",
    "Leg press (hinge)",
    "Low Incline Dumbbell Bench",
    "Military Press (Standing)",
    "Neutral Chin",
    "Overhead Press (Barbell)",
    "Overhead Press (Dumbbell)",
    "Pull Up",
    "Rack Pull - 1 Pin",
    "Rack Pull 2 Pin",
    "Rear delt fly",
    "Romanian Deadlift (Barbell)",
    "Rope Never Ending",
    "Rotator cuff work",
    "Seated Cable Row (close Grip)",
    "Seated Military Press",
    "Seated Military Press (Dumbbell)",
    "Seated Row",
    "Seated Shoulder Press (Barbell)",
    "Seated Shoulder Press (Dumbbell)",
    "Shoulder Press (Standing)",
    "Shrugs",
    "Shrugs (dumbbell)",
    "Skullcrusher (Barbell)",
    "Sling Shot Bench",
    "Sling Shot Incline",
    "Squat",
    "Squat (Barbell)",
    "Stairmaster",
    "T-bar Row",
    "Tricep Extension",
    "Tricep pushdown",
    "Weighted dips",
    "close grip Bench",
    "curl ez bar",
    "high bar squat",
    "kettlebell Swings",
    "lying Skullcrusher",
    "sumo deadlift",
  ];